--liquibase formatted sql

--changeset ps:10-LIQres-citizens-creation
CREATE TABLE LIQRES.T_CITIZENS
(
    ID  SERIAL PRIMARY KEY,
    NAME    VARCHAR(100),
    SURNAME VARCHAR(100),
    PATRONYMIC  VARCHAR(100),
    SFTMSTINP   TIMESTAMP DEFAULT NOW(),
    SFTMSTCHNGD   TIMESTAMP DEFAULT NOW()
);
--rollback DROP TABLE LIQRES.T_CITIZENS;

--changeset ps:20-LIQres-CITIZENS-creation
GRANT SELECT,INSERT,DELETE, UPDATE ON TABLE LIQRES.T_CITIZENS TO PUBLIC;
--rollback not required