--liquibase formatted sql

--changeset ps:10-LIQres-HOUSE2OWNERS-creation
CREATE TABLE LIQRES.T_HOUSE2OWNERS
(
    HOUSE REFERENCES T_HOUSE(ID),
    CITIZEN REFERENCES T_CITIZENS(ID),
    SFTMSTINP   TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (HOUSE,CITIZEN)
);
--rollback DROP TABLE LIQRES.T_HOUSE2OWNERS;

--changeset ps:20-LIQres-HOUSE2OWNERS-creation
GRANT SELECT,INSERT,DELETE, UPDATE ON TABLE LIQRES.T_HOUSE2OWNERS TO PUBLIC;
--rollback not required